### ISSUE TITLE
Mandatory avar table? Really?

### ISSUE THREAD

**Issue by justvanrossum** [justvanrossum/nabla#25]
Fontbakery:

```
Ensure variable fonts include an avar table.
Check ID: <FontBakeryCheck:com.google.fonts/check/mandatory_avar_table>
Most variable fonts should include an avar table to correctly define axes progression rates.

For example, a weight axis from 0% to 100% doesn't map directly to 100 to 1000, because a 10% progression from 0% may be too much to define the 200, while 90% may be too little to define the 900.

If the progression rates of axes is linear, this check can be ignored. Fontmake will also skip adding an avar table if the progression rates are linear. However, we still recommend designers visually proof each instance is at the desired weight, width etc.

🔥 fonts/Nabla.ttf
	• 🔥 FAIL
This variable font does not have an avar table. [code: missing-avar]
```

Can we just skip this check, or should I add a no-op avar table just to keep this check quiet? TBH it feels this FAIL should be a WARNING.

**Comment by davelab6** [comment]
@justvanrossum yes, that's fair, since the description is "most" not "all" then FAIL is heavy handed. @felipesanches when will you ship the check priorities feature so the avar check can be a high priority WARN?

**Comment by felipesanches** [comment]
Priority labeling of checks will be discussed is a separate fontbakery issue.

This issue is a perfect match to https://github.com/googlefonts/fontbakery/issues/3856 which was closed and discussion redirected to https://github.com/googlefonts/fontbakery/issues/3100
