### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jglovier** [justvanrossum/nabla#49]
Hi there, @justvanrossum! What an amazing typeface you've created, and extra cool that it is open source. ✨ 🙌 ✨ 

Would you consider adding a license to your repo that signals how you'd like it to allow it to be used? That would be helpful for lots of folks (whether individuals or teams) who need to take licensing restrictions into consideration when they use your font in their projects.

Warm regards,
Joel

**Comment by justvanrossum** [comment]
Thank you!

The license is here: https://github.com/justvanrossum/nabla/blob/main/OFL.txt

OFL (SIL Open Font License) is a common license for fonts, and I believe required for Google Fonts (such as this one).

I hope that answers your question.

**Comment by davelab6** [comment]
@jglovier I am genuinely curious how you were not able to find the license before filing an issue here :) where were you expecting to find this information and didn't? :)

**Comment by jglovier** [comment]
Oh! I didn't realize it was the OFL.txt file. I guess I'm just used to seeing the license as a `LICENSE` or `LICENSE.txt` file in the root that I completely overlooked the `OFL.txt` file.
