### ISSUE TITLE
Font-palette not supported by Firefox?

### ISSUE THREAD

**Issue by Christine-Gertsch** [justvanrossum/nabla#66]
According to https://caniuse.com/?search=font-palette, font-palettes should be supported by all current browser versions. Still, Firefox doesn’t display Nabla’s palettes reliably (?). Further tests with other color fonts worked fine, so I wonder whether this is a browser problem or a font issue.

**Comment by justvanrossum** [comment]
Perhaps Firefox prefers the SVG table over COLRv1? If I view https://nabla.typearture.com/ on Firefox it seems the variation axes also don't work.

**Comment by anthrotype** [comment]
in theory custom palettes should work because SVG table uses color variables referencing the CPAL table e.g. things like `stop-color="var(--color8, #FFFABE)"`

**Comment by justvanrossum** [comment]
Do we know whether:
- Firefox indeed prefers SVG over COLRv1?
- Firefox supports CPAL for SVG?

**Comment by anthrotype** [comment]
apparently my previous seemed to know, https://github.com/googlefonts/nanoemoji/issues/422#issuecomment-1235761749

> We already know that FireFox does not support font-palette and @font-palette-values yet: https://bugzilla.mozilla.org/show_bug.cgi?id=1461588.

**Comment by anthrotype** [comment]
that linked issue above was marked as completed 1 year ago.. I'm not sure why then it is still not working

**Comment by jfkthame** [comment]
> Do we know whether:
> 
>     * Firefox indeed prefers SVG over COLRv1?

Yes, I think that's currently the case (though probably should be reconsidered)...

> 
>     * Firefox supports CPAL for SVG?

No, CPAL is only supported for COLR fonts.

So I think this explains what you're seeing.

If you set `gfx.font_rendering.opentype_svg.enabled` to false in `about:config`, then you should see the COLRv1 glyphs being used.

**Comment by justvanrossum** [comment]
So after all it is a browser issue, not a font issue.

**Comment by Christine-Gertsch** [comment]
yes, that’s it. Thanks!
