### ISSUE TITLE
Interpolation problems in `Nabla[EDPT,EHLT].ttf`

### ISSUE THREAD

**Issue by behdad** [justvanrossum/nabla#67]
Hello!

This is an automatically-generated report about possible interpolation problems in `Nabla[EDPT,EHLT].ttf`, as found in the Google Fonts catalog.

The particular version of the font that was tested was [v1.002/nabla-fonts.zip](https://github.com/justvanrossum/nabla/releases/download/v1.002/nabla-fonts.zip).

To download a PDF version of this report with helpful visuals of the problems, click [here](https://github.com/behdad/google-fonts-ofl-interpolatable-results/raw/d6edb83d4370caca83be3043e41d51d20d6b6238/reports/Nabla%5BEDPT%2CEHLT%5D.ttf.pdf); Or to view it on the GitHub website, click [here](https://github.com/behdad/google-fonts-ofl-interpolatable-results/blob/d6edb83d4370caca83be3043e41d51d20d6b6238/reports/Nabla%5BEDPT%2CEHLT%5D.ttf.pdf).

The report follows:
```
Glyph acute was not compatible:
  Masters: '', 'EDPT=0.0':
    Contour order differs: [0, 1, 2] in '', [1, 0, 2] in 'EDPT=0.0'
Glyph acutecomb was not compatible:
  Masters: '', 'EDPT=0.0':
    Contour order differs: [0, 1, 2] in '', [1, 0, 2] in 'EDPT=0.0'
Glyph slash was not compatible:
  Masters: '', 'EDPT=0.0':
    Contour order differs: [0, 1, 2] in '', [2, 1, 0] in 'EDPT=0.0'
```

This report was generated using the `fonttools varLib.interpolatable` tool.  We understand that sometimes the tool generates false-positives.  Particularly for more complicated font designs.  If you did not find this report useful, please apologize and ignore & close it.

To give feedback about this report, please file an issue or open a discussion at [fonttools](https://github.com/fonttools/fonttools).

**Comment by justvanrossum** [comment]
It’s a false positive, as well as an incorrect suggested fix. The case is weird though, as in one of the sources the shape becomes a flat line (it interpolates to an invisible shape).

**Comment by behdad** [comment]
Yes, Nabla is one of the trickier ones. My apologies.

**Comment by justvanrossum** [comment]
No problem! It is very cool to see how sophisticated the tool is, and I’m impressed with how accurate it generally is.
